CREATE TABLE gpa (
    ID INTEGER PRIMARY KEY,
    username VARCHAR(20),
    password VARCHAR(20),
    classTitle1 VARCHAR(20),
    creditHours1 VARCHAR(20),
    earnedPoints1 VARCHAR(20),
    predictedPoints1 VARCHAR(20),
    totalPoints1 VARCHAR(20),
    classTitle2 VARCHAR(20),
    creditHours2 VARCHAR(20),
    earnedPoints2 VARCHAR(20),
    predictedPoints2 VARCHAR(20),
    totalPoints2 VARCHAR(20),
    classTitle3 VARCHAR(20),
    creditHours3 VARCHAR(20),
    earnedPoints3 VARCHAR(20),
    predictedPoints3 VARCHAR(20),
    totalPoints3 VARCHAR(20),
    classTitle4 VARCHAR(20),
    creditHours4 VARCHAR(20),
    earnedPoints4 VARCHAR(20),
    predictedPoints4 VARCHAR(20),
    totalPoints4 VARCHAR(20),
    classTitle5 VARCHAR(20),
    creditHours5 VARCHAR(20),
    earnedPoints5 VARCHAR(20),
    predictedPoints5 VARCHAR(20),
    totalPoints5 VARCHAR(20),
    cumulativeGPA VARCHAR(20),
    creditsEarned VARCHAR(20)
    );

